ProjetoAspNetAT/Controllers/PersonagensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjetoAspNetAT.Data;
using ProjetoAspNetAT.Models;

namespace ProjetoAspNetAT.Controllers
{
    public class PersonagensController : Controller
    {
        private readonly ProjetoAspNetATContext _context;

        public PersonagensController(ProjetoAspNetATContext context)
        {
            _context = context;
        }

        // GET: Personagens
        public async Task<IActionResult> Index()
        {
              return _context.Personagens != null ? 
                          View(await _context.Personagens.ToListAsync()) :
                          Problem("Entity set 'ProjetoAspNetATContext.Personagens'  is null.");
        }

        // GET: Personagens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Personagens == null)
            {
                return NotFound();
            }

            var personagens = await _context.Personagens
                .FirstOrDefaultAsync(m => m.Id == id);
            if (personagens == null)
            {
                return NotFound();
            }

            return View(personagens);
        }

        // GET: Personagens/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Personagens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Idade,Descricao,Criacao")] Personagens personagens)
        {
            if (ModelState.IsValid)
            {
                _context.Add(personagens);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(personagens);
        }

        // GET: Personagens/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Personagens == null)
            {
                return NotFound();
            }

            var personagens = await _context.Personagens.FindAsync(id);
            if (personagens == null)
            {
                return NotFound();
            }
            return View(personagens);
        }

        // POST: Personagens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Idade,Descricao,Criacao")] Personagens personagens)
        {
            if (id != personagens.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(personagens);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonagensExists(personagens.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(personagens);
        }

        // GET: Personagens/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Personagens == null)
            {
                return NotFound();
            }

            var personagens = await _context.Personagens
                .FirstOrDefaultAsync(m => m.Id == id);
            if (personagens == null)
            {
                return NotFound();
            }

            return View(personagens);
        }

        // POST: Personagens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Personagens == null)
            {
                return Problem("Entity set 'ProjetoAspNetATContext.Personagens'  is null.");
            }
            var personagens = await _context.Personagens.FindAsync(id);
            if (personagens != null)
            {
                _context.Personagens.Remove(personagens);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonagensExists(int id)
        {
          return (_context.Personagens?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ProjetoAspNetAT/Controllers/QuadrinhoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjetoAspNetAT.Data;
using ProjetoAspNetAT.Models;

namespace ProjetoAspNetAT.Controllers
{
    public class QuadrinhoesController : Controller
    {
        private readonly ProjetoAspNetATContext _context;

        public QuadrinhoesController(ProjetoAspNetATContext context)
        {
            _context = context;
        }

        // GET: Quadrinhoes
        public async Task<IActionResult> Index()
        {
              return _context.Quadrinho != null ? 
                          View(await _context.Quadrinho.ToListAsync()) :
                          Problem("Entity set 'ProjetoAspNetATContext.Quadrinho'  is null.");
        }

        // GET: Quadrinhoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Quadrinho == null)
            {
                return NotFound();
            }

            var quadrinho = await _context.Quadrinho
                .FirstOrDefaultAsync(m => m.Id == id);
            if (quadrinho == null)
            {
                return NotFound();
            }

            return View(quadrinho);
        }

        // GET: Quadrinhoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Quadrinhoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Autor,Quantidade")] Quadrinho quadrinho)
        {
            if (ModelState.IsValid)
            {
                _context.Add(quadrinho);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(quadrinho);
        }

        // GET: Quadrinhoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Quadrinho == null)
            {
                return NotFound();
            }

            var quadrinho = await _context.Quadrinho.FindAsync(id);
            if (quadrinho == null)
            {
                return NotFound();
            }
            return View(quadrinho);
        }

        // POST: Quadrinhoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Autor,Quantidade")] Quadrinho quadrinho)
        {
            if (id != quadrinho.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(quadrinho);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuadrinhoExists(quadrinho.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(quadrinho);
        }

        // GET: Quadrinhoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Quadrinho == null)
            {
                return NotFound();
            }

            var quadrinho = await _context.Quadrinho
                .FirstOrDefaultAsync(m => m.Id == id);
            if (quadrinho == null)
            {
                return NotFound();
            }

            return View(quadrinho);
        }

        // POST: Quadrinhoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Quadrinho == null)
            {
                return Problem("Entity set 'ProjetoAspNetATContext.Quadrinho'  is null.");
            }
            var quadrinho = await _context.Quadrinho.FindAsync(id);
            if (quadrinho != null)
            {
                _context.Quadrinho.Remove(quadrinho);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool QuadrinhoExists(int id)
        {
          return (_context.Quadrinho?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ProjetoAspNetAT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Registration of comics and characters</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoAspNetAT.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Registration of comics and characters</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personagens"> Personagem</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quadrinhoes"> Quadrinho</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"> Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @RenderSection("Footer", required: false)       &copy; 2023 - Registration of comics and characters
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>